# Generated by Django 4.1.9 on 2023-06-05 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinica",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cnpj", models.CharField(max_length=18, unique=True)),
                ("razao_social", models.CharField(max_length=100)),
                ("nome_fantasia", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=200)),
                ("telefone", models.CharField(max_length=20)),
                ("documentos_validacao", models.FileField(upload_to="documentos/clinicas")),
                ("data_inicio", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Especialidade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "nome",
                    models.CharField(
                        choices=[
                            ("Clínica Geral", "Clínica Geral / Medicina de Família"),
                            ("Pediatria", "Pediatria"),
                            ("Ginecologia e Obstetrícia", "Ginecologia e Obstetrícia"),
                            ("Cardiologia", "Cardiologia"),
                            ("Dermatologia", "Dermatologia"),
                            ("Ortopedia", "Ortopedia"),
                            ("Psiquiatria", "Psiquiatria"),
                            ("Oftalmologia", "Oftalmologia"),
                            ("Otorrinolaringologia", "Otorrinolaringologia"),
                            ("Endocrinologia", "Endocrinologia"),
                            ("Gastroenterologia", "Gastroenterologia"),
                            ("Neurologia", "Neurologia"),
                            ("Urologia", "Urologia"),
                            ("Odontologia", "Odontologia"),
                            ("Radiologia", "Radiologia"),
                            ("Oncologia", "Oncologia"),
                            ("Nefrologia", "Nefrologia"),
                            ("Reumatologia", "Reumatologia"),
                            ("Cirurgia Geral", "Cirurgia Geral"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medico",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("crm", models.CharField(max_length=20)),
                ("nome", models.CharField(max_length=100)),
                ("cpf", models.CharField(max_length=14)),
                ("rg", models.CharField(max_length=20)),
                ("endereco", models.CharField(max_length=200)),
                ("data_nascimento", models.DateField()),
                ("documentos_validacao", models.FileField(upload_to="documentos/")),
            ],
        ),
        migrations.CreateModel(
            name="Consulta",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.DateField()),
                ("horario", models.TimeField()),
                ("agendada", models.BooleanField(default=False)),
                ("clinica", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.clinica")),
                ("medico", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.medico")),
                (
                    "paciente",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AddField(
            model_name="clinica",
            name="especialidades",
            field=models.ManyToManyField(to="users.especialidade"),
        ),
    ]
