# Generated by Django 4.1.9 on 2023-06-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_clinica_especialidade_medico_consulta_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="cpf",
            field=models.CharField(blank=True, max_length=11, verbose_name="CPF"),
        ),
        migrations.AddField(
            model_name="user",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True, verbose_name="Data de Nascimento"),
        ),
        migrations.AddField(
            model_name="user",
            name="endereco",
            field=models.TextField(blank=True, verbose_name="Endereço"),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="first name"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="last name"),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=150, unique=True, verbose_name="username"),
        ),
    ]
