# Generated by Django 4.1.9 on 2023-06-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_name_user_cpf_user_data_nascimento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="social_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Social ID"),
        ),
    ]
